title: 'Machien'
author: 'Nerdlab'
description: 'Honderden schakels om iets heel eenvoudig te doen, dat is pas een machien. Rube Goldberg bouwde machines met grote complexiteit en beperkte meerwaarde. Op 6 mei in het Entrepot om 19u30 steken we onze machien in gang. Komt dat zien!'
exclude: ['_site','scss','*scss','Gem*','Guard*','*rb','.sass-cache','.git*','config.rb','*.md','*.json','docroot','node_modules','gulpfile.js','install.sh','lint.yml']
